name: 🌎 New translation
description: Add a new translation
labels: [i18n]
body:
  - type: input
    id: language
    attributes:
      label: What language are you adding?
      description: What it's called in the Spotify settings
      placeholder: e.g. Latin American Spanish
    validations:
      required: true

  - type: input
    id: menu-title
    attributes:
      label: Menu title
      description: Profile menu flyout title
      placeholder: e.g. "Hide podcasts"
    validations:
      required: true

  - type: input
    id: enabled
    attributes:
      label: Enabled
      placeholder: e.g. "Enabled"
    validations:
      required: true

  - type: input
    id: aggressive-mode
    attributes:
      label: Aggressive mode
      placeholder: e.g. "Aggressive mode"
    validations:
      required: true

  - type: input
    id: hide-audiobooks
    attributes:
      label: Hide audiobooks
      placeholder: e.g. "Hide audiobooks"
    validations:
      required: true

  - type: input
    id: audiobook-card-title
    attributes:
      label: Search page audiobook card title
      placeholder: e.g. "Audiobooks"
    validations:
      required: true
